const RECIPES={
  'chicken parmesan':[['boneless skinless chicken breasts','chicken breast family pack','1.5 lb'],['eggs','large eggs dozen','2'],['italian breadcrumbs','italian seasoned breadcrumbs','1.5 cups'],['parmesan cheese','grated parmesan cheese','0.75 cup'],['marinara sauce','marinara pasta sauce 24 oz','24 oz'],['mozzarella cheese','shredded mozzarella cheese 8 oz','8 oz'],['spaghetti','spaghetti pasta 16 oz','16 oz'],['olive oil','olive oil','2 tbsp'],['garlic','fresh garlic bulb','2 cloves'],['basil','fresh basil','optional']],
  'beef tacos':[['ground beef','ground beef 80 20 1 lb','1.5 lb'],['taco seasoning','taco seasoning packet','1 packet'],['tortillas','soft flour tortillas 10 count','10'],['shredded cheese','mexican blend shredded cheese 8 oz','8 oz'],['lettuce','shredded lettuce','1 bag'],['tomatoes','roma tomatoes','2'],['sour cream','sour cream 16 oz','8 oz'],['salsa','medium salsa 16 oz','1 jar']],
  'chicken alfredo':[['boneless skinless chicken breasts','chicken breast family pack','1.5 lb'],['fettuccine','fettuccine pasta 16 oz','16 oz'],['alfredo sauce','alfredo pasta sauce 15 oz','2 jars'],['parmesan cheese','grated parmesan cheese','0.5 cup'],['broccoli','fresh broccoli crowns','1 lb'],['garlic','fresh garlic bulb','2 cloves']],
  'lasagna':[['ground beef','ground beef 80 20 1 lb','1 lb'],['lasagna noodles','lasagna pasta noodles 16 oz','16 oz'],['marinara sauce','marinara pasta sauce 24 oz','2 jars'],['ricotta cheese','whole milk ricotta cheese 15 oz','15 oz'],['mozzarella cheese','shredded mozzarella cheese 16 oz','16 oz'],['parmesan cheese','grated parmesan cheese','0.5 cup'],['eggs','large eggs dozen','1']],
  'smash burgers':[['ground beef','ground beef 80 20 2 lb','2 lb'],['burger buns','hamburger buns 8 count','8'],['american cheese','american cheese slices','8 slices'],['onion','yellow onion','1'],['pickles','hamburger dill pickle chips','1 jar'],['ketchup','ketchup','1 bottle'],['mustard','yellow mustard','1 bottle']],
  'beef chili':[['ground beef','ground beef 80 20 2 lb','2 lb'],['kidney beans','kidney beans 15 oz can','2 cans'],['diced tomatoes','diced tomatoes 14.5 oz can','2 cans'],['tomato sauce','tomato sauce 15 oz can','1 can'],['chili seasoning','chili seasoning packet','1 packet'],['onion','yellow onion','1'],['shredded cheese','cheddar shredded cheese 8 oz','8 oz']],
  'meatloaf':[['ground beef','ground beef 80 20 2 lb','2 lb'],['eggs','large eggs dozen','2'],['breadcrumbs','plain breadcrumbs','1 cup'],['milk','whole milk half gallon','0.5 cup'],['ketchup','ketchup','1 bottle'],['onion','yellow onion','1']],
  'baked ziti':[['ziti pasta','ziti pasta 16 oz','16 oz'],['ground beef','ground beef 80 20 1 lb','1 lb'],['marinara sauce','marinara pasta sauce 24 oz','2 jars'],['ricotta cheese','whole milk ricotta cheese 15 oz','15 oz'],['mozzarella cheese','shredded mozzarella cheese 16 oz','16 oz'],['parmesan cheese','grated parmesan cheese','0.5 cup']]
};
const ALIASES={'chicken parm':'chicken parmesan','tacos':'beef tacos','alfredo':'chicken alfredo','smash burger':'smash burgers','chili':'beef chili','ziti':'baked ziti'};
const RETAILERS=['walmart','amazon','target','bestbuy','ebay','homedepot','lowes','costco','samsclub','etsy','newegg','chewy','wayfair'];
const PANTRY=new Set(['salt','black pepper','pepper','olive oil','vegetable oil','cooking oil','water']);
const jsonHeaders={'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,OPTIONS'};
function norm(v){return String(v||'').toLowerCase().replace(/\s+/g,' ').trim()}
export function parsePrefs(command){const t=norm(command);let retailer='walmart';for(const r of RETAILERS){const token=r==='bestbuy'?'best buy':r==='homedepot'?'home depot':r==='samsclub'?"sam's club":r;if(t.includes(token)||t.includes(r))retailer=r}const sm=t.match(/\bfor\s+(\d{1,2})(?:\s+(?:people|persons|guests|adults|kids))?\b/);const bm=t.match(/\b(?:under|max(?:imum)?|budget(?: of)?)\s*\$?\s*(\d+(?:\.\d{1,2})?)/);const exclusions=[];const er=/(?:\bno\b|\bwithout\b)\s+([^,.;]+?)(?=\s+(?:and|under|for|at|from|to|skip|cheapest|name brand)\b|[,.;]|$)/g;let m;while((m=er.exec(t)))exclusions.push(m[1].trim());return {retailer,servings:sm?Number(sm[1]):4,budget:bm?Number(bm[1]):null,skipPantry:/\bskip\s+(?:the\s+)?pantry/.test(t),exclusions}}
function findRecipe(command){const t=norm(command);for(const key of Object.keys(RECIPES))if(t.includes(key))return key;for(const [alias,key] of Object.entries(ALIASES))if(t.includes(alias))return key;return null}
function isExcluded(name,p){const n=norm(name);return p.exclusions.some(x=>n.includes(norm(x))||norm(x).includes(n))}
export function offlinePlan(command){const p=parsePrefs(command),key=findRecipe(command);if(!key)return null;let items=RECIPES[key].map(([name,searchTerm,amount])=>({name,searchTerm,amount,quantity:1})).filter(i=>!isExcluded(i.name,p));if(p.skipPantry)items=items.filter(i=>!PANTRY.has(norm(i.name)));return {ok:true,source:'worker-fallback',title:key.replace(/\b\w/g,c=>c.toUpperCase()),retailer:p.retailer,servings:p.servings,budget:p.budget,items}}
function promptFor(command){return `You are AutoCart. Convert the user's shopping request into strict JSON only, no markdown.\nReturn this exact shape: {"ok":true,"title":"...","retailer":"walmart","servings":4,"budget":40,"items":[{"name":"ingredient","searchTerm":"clean retailer search phrase with store package size but NEVER culinary amount like 2 cloves or 1 cup","amount":"culinary amount needed","quantity":1}]}.\nAllowed retailers: ${RETAILERS.join(', ')}. If a retailer is explicitly named, never switch it. Choose sensible retail package search terms. Do not add unrelated extras. User command: ${command}`}
function parseAiJson(value){const raw=typeof value==='string'?value:value?.response??value?.result??'';if(typeof raw==='object'&&raw)return raw;const s=String(raw||'').trim();try{return JSON.parse(s)}catch{}const a=s.indexOf('{'),b=s.lastIndexOf('}');if(a>=0&&b>a){try{return JSON.parse(s.slice(a,b+1))}catch{}}return null}
function cleanAiPlan(data,command){if(!data||!Array.isArray(data.items))return null;const p=parsePrefs(command),retailer=RETAILERS.includes(norm(data.retailer))?norm(data.retailer):p.retailer;let items=data.items.map(i=>({name:String(i.name||i.ingredient||'Item').trim(),searchTerm:String(i.searchTerm||i.search_term||i.name||i.ingredient||'').replace(/\s+/g,' ').trim(),amount:String(i.amount||i.requiredAmount||'').trim(),quantity:Math.max(1,Number(i.quantity)||1)})).filter(i=>i.searchTerm&&!isExcluded(i.name,p));if(p.skipPantry)items=items.filter(i=>!PANTRY.has(norm(i.name)));if(!items.length)return null;return {ok:true,source:'workers-ai',title:String(data.title||data.recipe||'AutoCart Plan'),retailer,servings:Number(data.servings)||p.servings,budget:data.budget==null?p.budget:Number(data.budget),items}}
export async function handleCommand(command,env){const text=String(command||'').trim();if(!text)throw new Error('command is required');const fallback=offlinePlan(text);if(fallback)return fallback;if(!env?.AI)return {ok:false,needsAI:true,error:'AI binding is not available and this request is outside the built-in recipe library.'};try{const result=await env.AI.run(env.AI_MODEL||'@cf/meta/llama-3.1-8b-instruct',{prompt:promptFor(text)});const cleaned=cleanAiPlan(parseAiJson(result),text);return cleaned||{ok:false,error:'AI returned an unusable shopping plan.'}}catch(error){console.error(JSON.stringify({event:'ai_command_failed',message:error?.message||String(error)}));return {ok:false,error:'AI planning failed. Try again or use a built-in recipe.'}}}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:jsonHeaders})}
export default {async fetch(request,env){const url=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:jsonHeaders});if(url.pathname==='/api/health'&&request.method==='GET')return json({ok:true,service:'autocart',aiEnabled:Boolean(env.AI),version:'3.1.0'});if(url.pathname==='/api/command'&&request.method==='POST'){const len=Number(request.headers.get('content-length')||0);if(len>32768)return json({ok:false,error:'Request too large'},413);let body;try{body=await request.json()}catch{return json({ok:false,error:'Invalid JSON'},400)}try{return json(await handleCommand(body.command,env))}catch(e){return json({ok:false,error:e.message},400)}}if(env.ASSETS)return env.ASSETS.fetch(request);return new Response('AutoCart',{status:200})}};
