'use strict';
const $=id=>document.getElementById(id);let currentPlan=null,queue=[],queueIndex=0,deferredInstall=null;
function nativeBridge(){return typeof Android!=='undefined'?Android:null}
function getConfiguredApi(){const saved=localStorage.getItem('autocartApiUrl')||'';if(saved)return saved.replace(/\/$/,'');try{return (nativeBridge()?.getApiUrl?.()||'').replace(/\/$/,'')}catch{return ''}}
function sameOriginApi(){if(!(location.protocol==='http:'||location.protocol==='https:'))return '';const h=location.hostname.toLowerCase();if(h==='localhost'||h==='127.0.0.1'||h==='::1')return '';return location.origin}
function activeApi(){return getConfiguredApi()||sameOriginApi()}
function setStatus(msg,cls=''){const e=$('status');if(!e)return;e.textContent=msg;e.className='status '+cls}
function setMode(){const explicit=getConfiguredApi();const hosted=sameOriginApi();$('apiUrl').value=explicit;const b=$('modeBadge');b.textContent=explicit||hosted?'AI READY':'OFFLINE READY';b.className='badge '+(explicit||hosted?'ok':'warn')}
function money(v){return v==null?'No budget set':'$'+Number(v).toFixed(2)+' budget'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function label(id){return AutoCartCore.retailerLabel?AutoCartCore.retailerLabel(id):String(id||'').toUpperCase()}
async function fetchPlan(command){const offline=AutoCartCore.buildOfflinePlan(command);const api=activeApi();if(!api)return offline;try{const r=await fetch(api+'/api/command',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({command})});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();return AutoCartCore.normalizeRemote(d,command)}catch(e){if(offline.ok)return {...offline,source:'offline-fallback',warning:'AI service unavailable; built-in recipe mode was used.'};return {...offline,error:'AI service unavailable and this recipe is not in the offline library.'}}}
function render(plan){currentPlan=plan;document.documentElement.dataset.autocartResult=plan&&plan.ok?'pass':'fail';if(!plan||!plan.ok){$('planCard').classList.add('hidden');$('queueCard').classList.add('hidden');setStatus(plan?.error||'Could not build that cart.','err');return}queue=AutoCartCore.makeQueue(plan);queueIndex=0;$('planCard').classList.remove('hidden');$('queueCard').classList.remove('hidden');$('planHead').innerHTML=`<div class="planhead"><div><div class="title">${esc(plan.title)}</div><div class="meta">${esc(label(plan.retailer))} · ${plan.servings||1} serving${Number(plan.servings||1)===1?'':'s'} · ${money(plan.budget)} · ${esc(plan.source)}</div></div><span class="badge">${plan.items.length} items</span></div>`;$('itemList').innerHTML=plan.items.map((i,n)=>`<div class="item"><div><div class="iname">${esc(i.name)}</div><div class="iamount">Need: ${esc(i.amount||'1 item')} · Search: ${esc(i.searchTerm)}</div></div><button class="btn secondary" data-open="${n}">Open</button></div>`).join('');document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openItem(Number(b.dataset.open)));updateQueue();setStatus(plan.warning||`Built ${plan.items.length} items for ${label(plan.retailer)}.`,'ok')}
async function run(){const command=$('command').value.trim();if(!command)return;$('run').disabled=true;setStatus('Building your cart…');try{render(await fetchPlan(command))}finally{$('run').disabled=false}}
function openExternal(url){try{if(nativeBridge()?.openExternal){nativeBridge().openExternal(url);return}}catch{}window.open(url,'_blank','noopener,noreferrer')}
function openItem(i){if(!queue[i])return;openExternal(queue[i].url)}
function updateQueue(){const total=queue.length,done=Math.min(queueIndex,total);$('queueText').textContent=total?`${done} of ${total} opened · ${label(currentPlan.retailer)}`:'No items';$('progressBar').style.width=(total?done/total*100:0)+'%';$('next').textContent=queueIndex>=total?'Restart handoff':'Open next item'}
function next(){if(!queue.length)return;if(queueIndex>=queue.length)queueIndex=0;openItem(queueIndex);queueIndex++;updateQueue()}
async function copyList(){if(!currentPlan)return;const text=`${currentPlan.title} — ${label(currentPlan.retailer)}\n`+currentPlan.items.map(i=>`• ${i.name}: ${i.amount||'1 item'}`).join('\n');try{if(nativeBridge()?.copyText){nativeBridge().copyText(text);setStatus('Shopping list copied.','ok');return}await navigator.clipboard.writeText(text);setStatus('Shopping list copied.','ok')}catch{setStatus('Could not copy automatically.','warn')}}
function clearAll(){currentPlan=null;queue=[];queueIndex=0;$('command').value='';$('planCard').classList.add('hidden');$('queueCard').classList.add('hidden');setStatus('Cleared.')}
function restart(){clearAll();$('command').value='Load chicken parmesan recipe to Walmart for 4 people under $40';setStatus('AutoCart restarted.','ok')}
function saveApi(){const v=$('apiUrl').value.trim().replace(/\/$/,'');if(v)localStorage.setItem('autocartApiUrl',v);else localStorage.removeItem('autocartApiUrl');setMode();setStatus(v?'AI endpoint saved.':'Using same-origin/offline mode.','ok')}
async function testApi(){const api=activeApi();if(!api){setStatus('Offline mode is ready. No Worker URL configured.','warn');return}setStatus('Testing connection…');try{const r=await fetch(api+'/api/health',{cache:'no-store'});const d=await r.json();if(!r.ok||!d.ok)throw new Error('Not healthy');setStatus(`Connected. AI ${d.aiEnabled?'enabled':'fallback enabled'}.`,'ok')}catch(e){setStatus('Connection test failed. Offline recipes and typed shopping lists still work.','warn')}}
function startVoice(){try{if(nativeBridge()?.startVoice){nativeBridge().startVoice();return}}catch{}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setStatus('Voice recognition is not available in this browser. Type the command instead.','warn');return}const r=new SR();r.lang='en-US';r.interimResults=false;r.onresult=e=>{$('command').value=e.results[0][0].transcript;run()};r.onerror=e=>setStatus('Voice input failed: '+e.error,'warn');r.start()}
window.onNativeVoice=text=>{$('command').value=text;run()};
window.AutoCartUI={render,setStatus,activeApi};
$('run').onclick=run;$('mic').onclick=startVoice;$('clear').onclick=clearAll;$('restart').onclick=restart;$('next').onclick=next;$('copy').onclick=copyList;$('saveApi').onclick=saveApi;$('testApi').onclick=testApi;document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{$('command').value='Load '+c.textContent;run()});$('command').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')run()});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('installBtn').style.display='inline-flex'});$('installBtn').onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('installBtn').style.display='none'};
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});setMode();if(new URLSearchParams(location.search).get('smoke')==='1')setTimeout(run,50);
