(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports) module.exports=api;
  else root.AutoCartCore=api;
})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const RETAILERS=['walmart','amazon','target','bestbuy','ebay','homedepot','lowes','costco','samsclub','etsy','newegg','chewy','wayfair'];
  const PANTRY=new Set(['salt','black pepper','pepper','olive oil','vegetable oil','cooking oil','water']);
  const RECIPES={
    'chicken parmesan':{aliases:['chicken parm','chicken parmesan'],items:[['boneless skinless chicken breasts','chicken breast family pack','1.5 lb'],['eggs','large eggs dozen','2'],['italian breadcrumbs','italian seasoned breadcrumbs','1.5 cups'],['parmesan cheese','grated parmesan cheese','0.75 cup'],['marinara sauce','marinara pasta sauce 24 oz','24 oz'],['mozzarella cheese','shredded mozzarella cheese 8 oz','8 oz'],['spaghetti','spaghetti pasta 16 oz','16 oz'],['olive oil','olive oil','2 tbsp'],['garlic','fresh garlic bulb','2 cloves'],['basil','fresh basil','optional']]},
    'beef tacos':{aliases:['tacos','beef tacos'],items:[['ground beef','ground beef 80 20 1 lb','1.5 lb'],['taco seasoning','taco seasoning packet','1 packet'],['tortillas','soft flour tortillas 10 count','10'],['shredded cheese','mexican blend shredded cheese 8 oz','8 oz'],['lettuce','shredded lettuce','1 bag'],['tomatoes','roma tomatoes','2'],['sour cream','sour cream 16 oz','8 oz'],['salsa','medium salsa 16 oz','1 jar']]},
    'chicken alfredo':{aliases:['chicken alfredo','alfredo'],items:[['boneless skinless chicken breasts','chicken breast family pack','1.5 lb'],['fettuccine','fettuccine pasta 16 oz','16 oz'],['alfredo sauce','alfredo pasta sauce 15 oz','2 jars'],['parmesan cheese','grated parmesan cheese','0.5 cup'],['broccoli','fresh broccoli crowns','1 lb'],['garlic','fresh garlic bulb','2 cloves']]},
    'lasagna':{aliases:['lasagna','lasagne'],items:[['ground beef','ground beef 80 20 1 lb','1 lb'],['lasagna noodles','lasagna pasta noodles 16 oz','16 oz'],['marinara sauce','marinara pasta sauce 24 oz','2 jars'],['ricotta cheese','whole milk ricotta cheese 15 oz','15 oz'],['mozzarella cheese','shredded mozzarella cheese 16 oz','16 oz'],['parmesan cheese','grated parmesan cheese','0.5 cup'],['eggs','large eggs dozen','1']]},
    'smash burgers':{aliases:['smash burgers','smashburger','smash burger'],items:[['ground beef','ground beef 80 20 2 lb','2 lb'],['burger buns','hamburger buns 8 count','8'],['american cheese','american cheese slices','8 slices'],['onion','yellow onion','1'],['pickles','hamburger dill pickle chips','1 jar'],['ketchup','ketchup','1 bottle'],['mustard','yellow mustard','1 bottle']]},
    'beef chili':{aliases:['beef chili','chili'],items:[['ground beef','ground beef 80 20 2 lb','2 lb'],['kidney beans','kidney beans 15 oz can','2 cans'],['diced tomatoes','diced tomatoes 14.5 oz can','2 cans'],['tomato sauce','tomato sauce 15 oz can','1 can'],['chili seasoning','chili seasoning packet','1 packet'],['onion','yellow onion','1'],['shredded cheese','cheddar shredded cheese 8 oz','8 oz']]},
    'meatloaf':{aliases:['meatloaf'],items:[['ground beef','ground beef 80 20 2 lb','2 lb'],['eggs','large eggs dozen','2'],['breadcrumbs','plain breadcrumbs','1 cup'],['milk','whole milk half gallon','0.5 cup'],['ketchup','ketchup','1 bottle'],['onion','yellow onion','1']]},
    'baked ziti':{aliases:['baked ziti','ziti'],items:[['ziti pasta','ziti pasta 16 oz','16 oz'],['ground beef','ground beef 80 20 1 lb','1 lb'],['marinara sauce','marinara pasta sauce 24 oz','2 jars'],['ricotta cheese','whole milk ricotta cheese 15 oz','15 oz'],['mozzarella cheese','shredded mozzarella cheese 16 oz','16 oz'],['parmesan cheese','grated parmesan cheese','0.5 cup']]}
  };
  function norm(s){return String(s||'').toLowerCase().replace(/[’']/g,"'").replace(/\s+/g,' ').trim()}
  function retailerFrom(text){const t=norm(text);const pairs=[['walmart',['walmart','wal mart']],['amazon',['amazon']],['target',['target']],['bestbuy',['best buy','bestbuy']],['ebay',['ebay']],['homedepot',['home depot']],['lowes',["lowe's",'lowes']],['costco',['costco']],['samsclub',["sam's club",'sams club']],['etsy',['etsy']],['newegg',['newegg']],['chewy',['chewy']],['wayfair',['wayfair']]];for(const [id,names] of pairs)if(names.some(n=>t.includes(n)))return id;return 'walmart'}
  function parseNumber(re,text,fallback){const m=norm(text).match(re);return m?Number(m[1]):fallback}
  function parseExclusions(text){const t=norm(text),out=[];const re=/(?:\bno\b|\bwithout\b)\s+([^,.;]+?)(?=\s+(?:and|under|for|at|from|to|skip|cheapest|name brand)\b|[,.;]|$)/g;let m;while((m=re.exec(t)))out.push(m[1].trim());return out}
  function parseCommand(text){const t=norm(text);return {raw:String(text||''),retailer:retailerFrom(t),servings:parseNumber(/\bfor\s+(\d{1,2})(?:\s+(?:people|persons|guests|adults|kids))?\b/,t,4),budget:parseNumber(/\b(?:under|max(?:imum)?|budget(?: of)?)\s*\$?\s*(\d+(?:\.\d{1,2})?)/,t,null),skipPantry:/\bskip\s+(?:the\s+)?pantry(?:\s+staples)?\b|\bno\s+pantry\s+staples\b/.test(t),cheapest:/\bcheapest\b|\blowest price\b|\bbudget\b/.test(t),nameBrand:/\bname[- ]brand\b|\bname brand only\b/.test(t),exclusions:parseExclusions(t)} }
  function recipeFrom(text){const t=norm(text);for(const [key,r] of Object.entries(RECIPES)){if(r.aliases.some(a=>t.includes(a)))return key}return null}
  function excluded(name,exclusions){const n=norm(name);return exclusions.some(x=>n.includes(norm(x))||norm(x).includes(n))}
  function buildOfflinePlan(text){const prefs=parseCommand(text),key=recipeFrom(text);if(!key)return {ok:false,needsAI:true,error:'This recipe is outside the offline library. Connect the AutoCart AI Worker and try again.',prefs};const recipe=RECIPES[key];let items=recipe.items.map(([name,searchTerm,amount])=>({name,searchTerm,amount,quantity:1}));items=items.filter(i=>!excluded(i.name,prefs.exclusions));if(prefs.skipPantry)items=items.filter(i=>!PANTRY.has(norm(i.name)));return {ok:true,source:'offline',title:key.replace(/\b\w/g,c=>c.toUpperCase()),servings:prefs.servings,budget:prefs.budget,retailer:prefs.retailer,preferences:prefs,items}}
  const searchBase={walmart:'https://www.walmart.com/search?q=',amazon:'https://www.amazon.com/s?k=',target:'https://www.target.com/s?searchTerm=',bestbuy:'https://www.bestbuy.com/site/searchpage.jsp?st=',ebay:'https://www.ebay.com/sch/i.html?_nkw=',homedepot:'https://www.homedepot.com/s/',lowes:'https://www.lowes.com/search?searchTerm=',costco:'https://www.costco.com/CatalogSearch?keyword=',samsclub:'https://www.samsclub.com/s/',etsy:'https://www.etsy.com/search?q=',newegg:'https://www.newegg.com/p/pl?d=',chewy:'https://www.chewy.com/s?query=',wayfair:'https://www.wayfair.com/keyword.php?keyword='};
  function handoffUrl(retailer,term){const id=RETAILERS.includes(retailer)?retailer:'walmart',base=searchBase[id];return base+encodeURIComponent(term)}
  function normalizeRemote(data,text){if(!data||typeof data!=='object')return buildOfflinePlan(text);const prefs=parseCommand(text);const items=Array.isArray(data.items)?data.items.map(i=>({name:String(i.name||i.ingredient||i.searchTerm||'Item'),searchTerm:String(i.searchTerm||i.search_term||i.name||i.ingredient||'').replace(/\s+/g,' ').trim(),amount:String(i.amount||i.requiredAmount||''),quantity:Number(i.quantity||1)||1})).filter(i=>i.searchTerm):[];if(!items.length)return buildOfflinePlan(text);return {ok:true,source:data.source||'ai',title:data.title||data.recipe||'AutoCart Plan',servings:Number(data.servings||prefs.servings)||prefs.servings,budget:data.budget??prefs.budget,retailer:RETAILERS.includes(data.retailer)?data.retailer:prefs.retailer,preferences:prefs,items:items.filter(i=>!excluded(i.name,prefs.exclusions)).filter(i=>!(prefs.skipPantry&&PANTRY.has(norm(i.name))))}}
  function makeQueue(plan){return (plan.items||[]).map((item,index)=>({...item,index,retailer:plan.retailer,url:handoffUrl(plan.retailer,item.searchTerm)}))}
  return {RETAILERS,RECIPES,parseCommand,recipeFrom,buildOfflinePlan,handoffUrl,normalizeRemote,makeQueue};
});
